services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
  
  livekit:
    image: livekit/livekit-server
    environment:
      LIVEKIT_KEYS: "${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}"
    command: --node-ip=0.0.0.0
    ports:
      - "7880:7880"
      - "7881:7881"
  
  frontend:  # ← Indentação correta (2 espaços)
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:5000/api
    ports:
      - "8080:8080"
    depends_on:
      - backend
      - livekit